### ISSUE TITLE
Haskell type error generated by vec2

### ISSUE THREAD

**Issue by iatorm** [barbuz/Husk#5]
Seen in this program:
https://tio.run/##yygtzv7//1HDwvxzW3X///9v8j/aWMdAR9c4FgA

It seems vec2 has a problem with function composition.

**Comment by iatorm** [comment]
This program gives an error already in the interpreter:
https://tio.run/##yygtzv7/P/hRw8L8c1t1H7VN@P//f7SxjoGOrnEsAA

**Comment by HPWiz** [comment]
Not sure of the correctness of my fix, but I edited the function "holds" in my copy of Expr.hs to require that types "t1,t2..s3" were Concrete. This fixes the current problem, but I don't know if it breaks anything else. Both functions now return [1,0,0]

**Comment by iatorm** [comment]
Fixed in latest commit. Also, `vec2` no longer admits functions as arguments.
