### ISSUE TITLE
Bug in numeric comparison

### ISSUE THREAD

**Issue by iatorm** [barbuz/Husk#6]
[This program](https://tio.run/##yygtzv7//9BynUedSx51Lv3//7@hnul/QwA) claims that `1.5` is both larger and smaller than `1`.

**Comment by H0tSauce** [comment]
Is there a reason why `toTruthy (TDbl d) = TInt $ roundAway d`? Because thats where the problem is.

**Comment by iatorm** [comment]
This has been fixed.
