### ISSUE TITLE
Wrong type signature

### ISSUE THREAD

**Issue by HPWiz** [barbuz/Husk#7]
The type of groupBy is [wrong](https://github.com/barbuz/Husk/blob/ec981ed63c9ffb264707c679c8f2a34edbc2e2b8/Builtins.hs#L290). It should end in `lst (lst x)`

**Comment by H0tSauce** [comment]
It makes this [code](https://tio.run/##yygtzv7/P9j2UcMejZBcjYc7Gx@1TTRK10w7tNzWB8hzKf3//390tIGOgY6hjmGsTjSQBLINgCwDMAsiBmbHxgIA) error

**Comment by iatorm** [comment]
This has been fixed.
