### ISSUE TITLE
Subscripts are now slower

### ISSUE THREAD

**Issue by HPWiz** [barbuz/Husk#8]
I believe the last commit has made programs with subscripts slower, see [this](https://tio.run/##yygtzv6vkHtiffGjpsaiQ9v@Z4TmAlmPOpccWgik7bge7lyQFlz1qHGD@6Npm/7//x9tqGOkY6pjomOsYx7LFW1ooKNrqGNoBGTqmuvoWujomupAhIAiljoWOuY6ZjqmEIWGxjqG5jpGhlAeGFkCCSAfYiBYdSwA) for example

**Comment by iatorm** [comment]
Should be fixed in latest commit.
